### ISSUE TITLE
requirement not able to download: onboard==1.1.2

### ISSUE THREAD

**Issue by pieterhouwen** [rascal999/torc#1]
This package cannot be found 

What can be found:

root@supersecretkali:~/torc# pip search onboard
genderly (0.105)           - A library to classify an indian name as Male or Female. Mainly focused around making the user onboarding smooth for
                             eCommerce merchants by pre-filling the gender for their users during a signup.
onegov.onboarding (0.3.6)  - Onboarding for OneGov Cloud applications.
pypackager (4.0.1)         - PyPackager is an onboard developpers toolswhich is usefull to create sources and binaryMaemo/Harmattan/MeeGo package.
root@supersecretkali:~/torc# 

I don't think that these will do, can I just skip that one package and resume?

My OS is Kali Linux amd64 4.9.30

I'm not sure why the text is all screwed up in this post

**Comment by pieterhouwen** [comment]
pygobject is also not available
urllib3-dev is not available, highest version at the moment = 1.21.1
Also Flask doesn't work even though it's installed

root@supersecretkali:~# torc
Traceback (most recent call last):
  File "/usr/local/bin/torc", line 11, in <module>
    load_entry_point('torc==0.1.0', 'console_scripts', 'torc')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/torc-0.1.0-py3.5.egg/torc/__init__.py", line 14, in <module>
    from flask import Flask, make_response, send_file, jsonify
ImportError: No module named 'flask'
root@supersecretkali:~# 

I ran: pip install -r requirements.txt
./setup.py install
torc
